name: Build Vibe Sourcer

on:
  workflow_dispatch:

jobs:
  build-extension:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build and zip extension
        run: pnpm zip
      - name: Upload extension artifact
        uses: actions/upload-artifact@v3
        with:
          name: vibe-sourcer-extension
          path: dist-zip/*.zip
